#!/bin/bash
# Deploy config files and reload affected services.
#
# Subcommand mode (manifest-based file deployment):
#   roost-apply [diff|push|list] [file-filter...]
#
# Flag mode (direct service reload):
#   roost-apply [--all] [--cloudflare] [--caddy] [--ntfy] [--systemd] [--cron]
#
# Options:
#   -y, --yes    Skip confirmation prompts (push only)
set -euo pipefail
source "$(dirname "$(readlink -f "$0")")/_hook-env.sh"

# --- Paths ---
_HOOKS_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
_ROOST_DIR="$(cd "$_HOOKS_DIR/../.." && pwd)"
REPO_DIR="$_ROOST_DIR/code/server"

# --- Output helpers ---
info() { echo "  [*] $1"; }
ok()   { echo "  [+] $1"; }
skip() { echo "  [-] $1 (skipped)"; }
warn() { echo "  [!] $1"; }

# ============================================
# Environment
# ============================================

source_env() {
    local sync_env="$_ROOST_DIR/.sync-env"
    [ -f "$sync_env" ] || regenerate_sync_env "$sync_env"
    source "$sync_env"
    ROOST_DIR_NAME="${ROOST_DIR_NAME:?ROOST_DIR_NAME not set}"
    TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-$ROOST_DIR_NAME}"
    HOME_DIR="/home/$USERNAME"
    ROOST_DIR="$HOME_DIR/$ROOST_DIR_NAME"
}

# Regenerate .sync-env from derivable values. deploy.sh will overwrite on next run.
regenerate_sync_env() {
    local sync_env="$1"
    local dir_name; dir_name=$(basename "$_ROOST_DIR")
    local owner; owner=$(stat -c '%U' "$_ROOST_DIR")
    local host; host=$(hostname)
    warn "$sync_env missing; regenerating from derived values"
    cat > "$sync_env" <<EOF
# Auto-regenerated by roost-apply on $(date -Iseconds).
# deploy.sh will overwrite on next deploy. DOMAIN left empty; set via .env + deploy.sh.
SERVER_NAME="$host"
USERNAME="$owner"
DOMAIN=""
ROOST_DIR_NAME="$dir_name"
CLOUDFLARE_TUNNEL_NAME="$dir_name"
EOF
    logger -t roost/roost-apply "Regenerated $sync_env"
}

# --- Dynamic variables (lazy-cached) ---
_RESOLVED_TAILSCALE_IP=""
_RESOLVED_TUNNEL_ID=""

tailscale_ip() {
    if [ -z "$_RESOLVED_TAILSCALE_IP" ]; then
        _RESOLVED_TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || true)
        if [ -z "$_RESOLVED_TAILSCALE_IP" ]; then
            warn "Could not resolve Tailscale IP"
        fi
    fi
    echo "$_RESOLVED_TAILSCALE_IP"
}

tunnel_id() {
    if [ -z "$_RESOLVED_TUNNEL_ID" ]; then
        # .base is the source of truth; .yml is the assembled output.
        # Fall back to .yml on pre-migration servers.
        for _f in /etc/cloudflared/config.yml.base /etc/cloudflared/config.yml; do
            _RESOLVED_TUNNEL_ID=$(sudo grep -oP '^tunnel: \K.+' "$_f" 2>/dev/null || true)
            [ -n "$_RESOLVED_TUNNEL_ID" ] && break
        done
        if [ -z "$_RESOLVED_TUNNEL_ID" ]; then
            warn "Could not resolve TUNNEL_ID from /etc/cloudflared/config.yml{,.base}"
        fi
    fi
    echo "$_RESOLVED_TUNNEL_ID"
}

# ============================================
# File Manifest
# ============================================

# Each entry: repo_path|server_path|transform|service_action
# Transforms: plain, plain+x, envsubst:<VARS>, sed-roost
# Service actions (comma-separated):
#   reload-or-restart:<unit>  restart:<unit>  daemon-reload
#   daemon-reload,restart:<unit>  run:<command>  (empty = none)

define_manifest() {
    # Category A: User files under ~/roost/ (no root needed)
    cat <<'MANIFEST_A'
files/settings.json|$ROOST_DIR/claude/settings.json|sed-roost|
files/hooks/_hook-env.sh|$ROOST_DIR/claude/hooks/_hook-env.sh|plain+x|
files/hooks/session-lock.sh|$ROOST_DIR/claude/hooks/session-lock.sh|plain+x|
files/hooks/session-unlock.sh|$ROOST_DIR/claude/hooks/session-unlock.sh|plain+x|
files/hooks/reflect.sh|$ROOST_DIR/claude/hooks/reflect.sh|plain+x|
files/hooks/notify.sh|$ROOST_DIR/claude/hooks/notify.sh|plain+x|
files/hooks/statusline.sh|$ROOST_DIR/claude/hooks/statusline.sh|plain+x|
files/hooks/health-check.sh|$ROOST_DIR/claude/hooks/health-check.sh|plain+x|
files/hooks/scheduled-task.sh|$ROOST_DIR/claude/hooks/scheduled-task.sh|plain+x|
files/hooks/run-scheduled-task.sh|$ROOST_DIR/claude/hooks/run-scheduled-task.sh|plain+x|
files/hooks/auto-update.sh|$ROOST_DIR/claude/hooks/auto-update.sh|plain+x|
files/hooks/ram-monitor.sh|$ROOST_DIR/claude/hooks/ram-monitor.sh|plain+x|
files/hooks/cloudflare-assemble.sh|$ROOST_DIR/claude/hooks/cloudflare-assemble.sh|plain+x|
files/hooks/reflect.md|$ROOST_DIR/claude/hooks/reflect.md|sed-roost|
files/hooks/roost-apply.sh|$ROOST_DIR/claude/hooks/roost-apply.sh|plain+x|
files/hooks/roost-net.sh|$ROOST_DIR/claude/hooks/roost-net.sh|plain+x|
files/travel/travel-health.sh|$ROOST_DIR/claude/hooks/health-check-apps.sh|plain+x|
files/shell/bashrc.sh|$HOME_DIR/.bashrc.d/roost.sh|plain|
files/private/code-CLAUDE.md|$ROOST_DIR/code/CLAUDE.md|plain|
files/private/global-CLAUDE.md|$ROOST_DIR/claude/CLAUDE.md|plain|
files/skills/html2markdown/SKILL.md|$ROOST_DIR/claude/skills/html2markdown/SKILL.md|plain|
files/skills/havelock-api/SKILL.md|$ROOST_DIR/claude/skills/havelock-api/SKILL.md|plain|
MANIFEST_A

    # Category B: System files (root needed, may require service restarts)
    cat <<'MANIFEST_B'
files/Caddyfile|/etc/caddy/Caddyfile|envsubst:TAILSCALE_IP,DOMAIN|reload-or-restart:caddy
files/apps.caddy|/etc/caddy/sites-enabled/apps.caddy|plain|reload-or-restart:caddy
files/cloudflare-config.yml|/etc/cloudflared/config.yml.base|envsubst:TUNNEL_ID,TUNNEL_NAME|run:~/roost/claude/hooks/cloudflare-assemble.sh,restart:cloudflared
files/cloudflare-config.yml|$HOME_DIR/.cloudflared/config.yml|envsubst:TUNNEL_ID,TUNNEL_NAME|
files/ntfy-server.yml|/etc/ntfy/server.yml|plain|restart:ntfy
files/et.cfg|/etc/et.cfg|envsubst:TAILSCALE_IP|restart:et
files/caddy-tailscale.conf|/etc/systemd/system/caddy.service.d/tailscale.conf|plain|daemon-reload
files/glances.service|/etc/systemd/system/glances.service|envsubst:USERNAME|daemon-reload,restart:glances
files/ram-monitor.service|/etc/systemd/system/ram-monitor.service|envsubst:USERNAME,HOME_DIR,ROOST_DIR_NAME|daemon-reload
files/ram-monitor.timer|/etc/systemd/system/ram-monitor.timer|envsubst:USERNAME,HOME_DIR,ROOST_DIR_NAME|daemon-reload,restart:ram-monitor.timer
files/cron-roost|/etc/cron.d/$ROOST_DIR_NAME|envsubst:USERNAME,HOME_DIR,ROOST_DIR_NAME|
files/tmux.conf|$HOME_DIR/.tmux.conf|plain|run:tmux source-file ~/.tmux.conf
files/sshd/50-clip-forward.conf|/etc/ssh/sshd_config.d/50-clip-forward.conf|plain|restart:ssh
files/tailscaled-iptables.conf|/etc/systemd/system/tailscaled.service.d/iptables-pin.conf|plain|daemon-reload,restart:tailscaled
files/travel/xray.service|/etc/systemd/system/xray.service|plain|daemon-reload,restart:xray
files/travel/xray-boot-guard|/usr/local/bin/xray-boot-guard|plain+x|restart:xray
files/travel/xray-logrotate.conf|/etc/logrotate.d/xray|plain|
files/travel/keys-init.sh|/etc/roost-travel/keys-init.sh|plain+x|
files/travel/proton-routing.sh|/etc/roost-travel/proton-routing.sh|plain+x|
files/travel/proton-keepalive-check|/usr/local/bin/proton-keepalive-check|plain+x|
files/travel/proton-keepalive.service|/etc/systemd/system/proton-keepalive.service|plain|daemon-reload
files/travel/proton-keepalive.timer|/etc/systemd/system/proton-keepalive.timer|plain|daemon-reload
files/travel/proton-routing-ensure.service|/etc/systemd/system/proton-routing-ensure.service|plain|daemon-reload
files/travel/proton-routing-ensure.timer|/etc/systemd/system/proton-routing-ensure.timer|plain|daemon-reload
files/travel/apt-roost-travel.conf|/etc/apt/apt.conf.d/99-roost-travel.conf|plain|
files/travel/wg-proton.service.d/roost.conf|/etc/systemd/system/wg-quick@wg-proton.service.d/roost.conf|plain|daemon-reload
files/travel/proton.conf.example|/etc/roost-travel/proton.conf.example|plain|
files/travel/travel-cloudflare.yml.tmpl|/etc/roost-travel/travel-cloudflare.yml|envsubst:DOMAIN|
MANIFEST_B
}

# Expand variables in server path.
# $ROOST_DIR_NAME must be expanded before $ROOST_DIR to avoid partial matching.
expand_path() {
    local path="$1"
    path="${path//\$ROOST_DIR_NAME/$ROOST_DIR_NAME}"
    path="${path//\$HOME_DIR/$HOME_DIR}"
    path="${path//\$ROOST_DIR/$ROOST_DIR}"
    path="${path//\$USERNAME/$USERNAME}"
    echo "$path"
}

# Check if a file needs root to write
needs_root() {
    # Assume root ownership for any absolute path outside /home and /tmp.
    # Previously only matched /etc/*, which broke deploys to /usr/local/bin/*
    # and similar root-owned paths (e.g. proton-keepalive-check after it had
    # already been installed via sudo by setup/travel-vpn.sh).
    case "$1" in
        /home/*|/tmp/*) return 1 ;;
        /*) return 0 ;;
        *) return 1 ;;
    esac
}

# ============================================
# Transforms
# ============================================

# Render a repo file with its transform applied
render_file() {
    local repo_path="$1"
    local transform="$2"
    local full_path="$REPO_DIR/$repo_path"

    if [ ! -f "$full_path" ]; then
        return 1
    fi

    case "$transform" in
        plain|plain+x)
            cat "$full_path"
            ;;
        sed-roost)
            sed "s|~/roost/|~/$ROOST_DIR_NAME/|g" "$full_path"
            ;;
        envsubst:*)
            local vars_csv="${transform#envsubst:}"
            local var_list=""
            IFS=',' read -ra var_names <<< "$vars_csv"
            for v in "${var_names[@]}"; do
                var_list+=" \$$v"
            done

            # Export required variables for envsubst
            export TUNNEL_ID
            TUNNEL_ID=$(tunnel_id)
            export TAILSCALE_IP
            TAILSCALE_IP=$(tailscale_ip)
            export TUNNEL_NAME
            export USERNAME
            export HOME_DIR
            export ROOST_DIR_NAME
            export DOMAIN
            export HETZNER_PUBLIC_IPV4
            export HETZNER_PUBLIC_IPV6

            # Guard: abort if any required variable is empty
            for v in "${var_names[@]}"; do
                if [ -z "${!v:-}" ]; then
                    echo "Error: $v is empty, refusing to render $full_path" >&2
                    return 1
                fi
            done

            envsubst "$var_list" < "$full_path"
            ;;
        *)
            echo "Error: Unknown transform '$transform'" >&2
            return 1
            ;;
    esac
}

# ============================================
# Manifest Filtering
# ============================================

get_manifest() {
    local line
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        local repo_path="${line%%|*}"

        if [ ${#FILE_FILTERS[@]} -gt 0 ]; then
            local match=false
            for filter in "${FILE_FILTERS[@]}"; do
                if [[ "$repo_path" == *"$filter"* ]] || [[ "$filter" == *"$repo_path"* ]]; then
                    match=true
                    break
                fi
            done
            [ "$match" = false ] && continue
        fi

        echo "$line"
    done <<< "$(define_manifest)"
}

# Read deployed file content, using sudo for root-owned paths
read_deployed() {
    local server_path="$1"
    if needs_root "$server_path"; then
        sudo cat "$server_path" 2>/dev/null || true
    else
        cat "$server_path" 2>/dev/null || true
    fi
}

# Check if deployed file exists, using sudo for root-owned paths
deployed_exists() {
    local server_path="$1"
    if needs_root "$server_path"; then
        sudo test -f "$server_path"
    else
        test -f "$server_path"
    fi
}

# ============================================
# Subcommand: list
# ============================================

cmd_list() {
    source_env
    echo ""
    echo "  Managed files:"
    echo ""

    printf "  %-45s  %-50s  %s\n" "REPO PATH" "DEPLOYED PATH" "TRANSFORM"
    printf "  %-45s  %-50s  %s\n" "---------" "-------------" "---------"

    while IFS='|' read -r repo_path server_path transform service_action; do
        server_path=$(expand_path "$server_path")
        printf "  %-45s  %-50s  %s\n" "$repo_path" "$server_path" "$transform"
    done <<< "$(get_manifest)"
    echo ""
}

# ============================================
# Subcommand: diff
# ============================================

cmd_diff() {
    source_env
    local has_diff=false
    local missing_local=()
    local missing_dest=()

    while IFS='|' read -r -u3 repo_path server_path transform service_action; do
        server_path=$(expand_path "$server_path")
        local full_repo_path="$REPO_DIR/$repo_path"

        if [ ! -f "$full_repo_path" ]; then
            missing_local+=("$repo_path")
            continue
        fi

        local local_content
        local_content=$(render_file "$repo_path" "$transform") || { warn "Failed to render $repo_path, skipping"; continue; }

        if ! deployed_exists "$server_path"; then
            missing_dest+=("$repo_path -> $server_path")
            continue
        fi

        local dest_content
        dest_content=$(read_deployed "$server_path")

        local diff_output
        diff_output=$(diff -u \
            --label "deployed:$server_path" \
            --label "repo:$repo_path (rendered)" \
            <(echo "$dest_content") \
            <(echo "$local_content") \
        ) || true

        if [ -n "$diff_output" ]; then
            has_diff=true
            echo ""
            echo "--- $repo_path -> $server_path [$transform]"
            echo "$diff_output"
        fi
    done 3<<< "$(get_manifest)"

    if [ ${#missing_local[@]} -gt 0 ]; then
        echo ""
        warn "Local files not found (not yet created?):"
        for f in "${missing_local[@]}"; do
            echo "    $f"
        done
    fi

    if [ ${#missing_dest[@]} -gt 0 ]; then
        echo ""
        warn "Deployed files not found (not yet deployed?):"
        for f in "${missing_dest[@]}"; do
            echo "    $f"
        done
    fi

    if [ "$has_diff" = false ] && [ ${#missing_local[@]} -eq 0 ] && [ ${#missing_dest[@]} -eq 0 ]; then
        echo ""
        ok "All files in sync"
    fi
    echo ""
}

# ============================================
# Subcommand: push
# ============================================

cmd_push() {
    source_env
    logger -t "$_HOOK_TAG" "Push started"

    # Phase 1: Compute diffs and collect changes
    local -a changed_repos=()
    local -a changed_servers=()
    local -a changed_transforms=()
    local -a changed_services=()
    local -a changed_contents=()
    local -a diff_outputs=()

    while IFS='|' read -r -u3 repo_path server_path transform service_action; do
        server_path=$(expand_path "$server_path")
        local full_repo_path="$REPO_DIR/$repo_path"

        if [ ! -f "$full_repo_path" ]; then
            skip "$repo_path (local file missing)"
            continue
        fi

        local local_content
        local_content=$(render_file "$repo_path" "$transform") || { warn "Failed to render $repo_path, skipping"; continue; }

        local dest_content
        dest_content=$(read_deployed "$server_path")

        local diff_output
        diff_output=$(diff -u \
            --label "deployed:$server_path" \
            --label "repo:$repo_path (rendered)" \
            <(echo "$dest_content") \
            <(echo "$local_content") \
        ) || true

        if [ -n "$diff_output" ]; then
            changed_repos+=("$repo_path")
            changed_servers+=("$server_path")
            changed_transforms+=("$transform")
            changed_services+=("$service_action")
            changed_contents+=("$local_content")
            diff_outputs+=("$diff_output")
        fi
    done 3<<< "$(get_manifest)"

    if [ ${#changed_repos[@]} -eq 0 ]; then
        ok "Nothing to push (all files in sync)"
        return 0
    fi

    # Phase 2: Show preview
    echo ""
    echo "  Changes to push:"
    echo ""
    for i in "${!changed_repos[@]}"; do
        echo "--- ${changed_repos[$i]} -> ${changed_servers[$i]} [${changed_transforms[$i]}]"
        echo "${diff_outputs[$i]}"
        echo ""
    done

    # Phase 3: Confirm
    if [ "$AUTO_CONFIRM" = false ]; then
        echo "  ${#changed_repos[@]} file(s) will be updated."
        read -rp "  Push? [y/N] " confirm
        case "$confirm" in
            [yY]|[yY][eE][sS]) ;;
            *)
                echo "  Aborted."
                return 0
                ;;
        esac
    fi

    # Phase 4: Write files
    local need_daemon_reload=false
    local -A services_to_restart=()
    local -a run_commands=()

    echo ""
    for i in "${!changed_repos[@]}"; do
        local sp="${changed_servers[$i]}"
        local transform="${changed_transforms[$i]}"
        local content="${changed_contents[$i]}"
        local service="${changed_services[$i]}"

        # Ensure parent directory exists and write file
        local parent_dir
        parent_dir=$(dirname "$sp")
        if needs_root "$sp"; then
            sudo mkdir -p "$parent_dir"
            printf '%s\n' "$content" | sudo tee "$sp" > /dev/null
            # sudo tee preserves existing non-root ownership; enforce root:root 0644 for /etc/*
            sudo chown root:root "$sp"
            sudo chmod 644 "$sp"
        else
            mkdir -p "$parent_dir"
            printf '%s\n' "$content" > "$sp"
        fi

        # Set executable if needed
        if [[ "$transform" == *"+x"* ]]; then
            if needs_root "$sp"; then
                sudo chmod +x "$sp"
            else
                chmod +x "$sp"
            fi
        fi

        # Track service actions
        IFS=',' read -ra actions <<< "$service"
        for action in "${actions[@]}"; do
            action="${action# }"; action="${action% }"
            [ -z "$action" ] && continue
            case "$action" in
                daemon-reload)
                    need_daemon_reload=true
                    ;;
                run:*)
                    run_commands+=("${action#run:}")
                    ;;
                *)
                    services_to_restart["$action"]=1
                    ;;
            esac
        done

        ok "${changed_repos[$i]} -> $sp"
    done

    # Phase 5: daemon-reload → run commands → restart services.
    # Run commands fire before restarts so post-write transforms (e.g.
    # cloudflare-assemble.sh building config.yml from config.yml.base +
    # fragments) land before the service picks up its new config.
    if [ "$need_daemon_reload" = true ]; then
        info "Running systemctl daemon-reload..."
        sudo systemctl daemon-reload
        ok "daemon-reload"
    fi

    # Run commands are from the hardcoded manifest only (no user input)
    for cmd in "${run_commands[@]}"; do
        info "Running: $cmd"
        bash -c "$cmd" || true
    done

    local restart_failed=()
    for action in "${!services_to_restart[@]}"; do
        local verb="${action%%:*}"
        local unit="${action#*:}"
        info "Running systemctl $verb $unit..."
        if sudo systemctl "$verb" "$unit"; then
            ok "$verb $unit"
        else
            restart_failed+=("$unit")
            warn "Failed: systemctl $verb $unit"
        fi
    done

    echo ""
    ok "Push complete (${#changed_repos[@]} file(s) updated)"
    logger -t "$_HOOK_TAG" "Push complete: ${#changed_repos[@]} file(s) updated"

    # Notify on failures
    if [ ${#restart_failed[@]} -gt 0 ]; then
        ntfy_send -t "roost-apply: restart failures" -p "high" \
            "Failed to restart: ${restart_failed[*]}"
    fi
}

# ============================================
# Flag mode: direct service reload
# ============================================

cmd_flag_reload() {
    source_env
    logger -t "$_HOOK_TAG" "Flag reload started"

    local reload_failed=()

    if $FLAG_ALL || $FLAG_CLOUDFLARE; then
        if [ -x "$_HOOKS_DIR/cloudflare-assemble.sh" ]; then
            info "Running cloudflare assembly..."
            "$_HOOKS_DIR/cloudflare-assemble.sh"
            ok "Cloudflare config assembled"
        fi
        info "Restarting cloudflared..."
        if sudo systemctl restart cloudflared; then
            ok "cloudflared restarted"
        else
            reload_failed+=("cloudflared")
            warn "Failed: systemctl restart cloudflared"
        fi
    fi

    if $FLAG_ALL || $FLAG_SYSTEMD; then
        info "Running systemctl daemon-reload..."
        sudo systemctl daemon-reload
        ok "daemon-reload"
    fi

    if $FLAG_ALL || $FLAG_CADDY; then
        info "Reloading Caddy..."
        if sudo systemctl reload-or-restart caddy; then
            ok "Caddy reloaded"
        else
            reload_failed+=("caddy")
            warn "Failed: systemctl reload-or-restart caddy"
        fi
    fi

    if $FLAG_ALL || $FLAG_NTFY; then
        info "Restarting ntfy..."
        if sudo systemctl restart ntfy; then
            ok "ntfy restarted"
        else
            reload_failed+=("ntfy")
            warn "Failed: systemctl restart ntfy"
        fi
    fi

    if $FLAG_ALL || $FLAG_SYSTEMD; then
        for unit in glances ram-monitor.timer; do
            info "Restarting $unit..."
            if sudo systemctl restart "$unit"; then
                ok "$unit restarted"
            else
                reload_failed+=("$unit")
                warn "Failed: systemctl restart $unit"
            fi
        done
    fi

    if $FLAG_ALL || $FLAG_CRON; then
        ok "Cron (auto-reloads, no action needed)"
    fi

    if $FLAG_ALL || $FLAG_XRAY; then
        local template="$REPO_DIR/files/travel/xray-config.json.tmpl"
        local state="/etc/roost-travel/state.env"
        if [ ! -f "$template" ]; then
            warn "Missing Xray template: $template"
        elif ! sudo test -r "$state"; then
            warn "Missing state.env: $state (run setup/travel-vpn.sh or keys-init.sh first)"
        else
            info "Re-rendering /etc/xray/config.json..."
            local tmp
            # .json suffix so `xray run -test` autodetects the format.
            tmp=$(mktemp --suffix=.json)
            set -a
            # shellcheck disable=SC1090
            eval "$(sudo cat "$state")"
            set +a
            # Sourced helper defines $XRAY_ENVSUBST_VARS — kept identical with
            # files/setup/travel-vpn.sh's render path to avoid silent allowlist drift.
            # shellcheck disable=SC1091
            source "$REPO_DIR/files/travel/_envsubst-vars.sh"
            envsubst "$XRAY_ENVSUBST_VARS" \
                < "$template" > "$tmp"
            # Validate before install: a parse-time error (broken JSON, wrong
            # types, missing required fields) would otherwise install
            # successfully and crash xray on the subsequent restart, taking
            # down all paths. `xray run -test` catches that class. Note: xray
            # accepts unknown fields silently, so this guard does NOT catch
            # the field-name-typo class (use upstream docs to verify).
            if ! sudo /usr/local/bin/xray run -test -c "$tmp" >/dev/null 2>&1; then
                local err
                err=$(sudo /usr/local/bin/xray run -test -c "$tmp" 2>&1 || true)
                warn "xray config validation failed; keeping previous /etc/xray/config.json"
                echo "$err" | sed 's/^/    /' >&2
                ntfy_send -t "roost-apply: xray config invalid" -p "high" \
                    "Rendered xray config failed 'xray run -test'; previous config kept. Check journalctl -t roost/roost-apply." \
                    || true
                rm -f "$tmp"
                reload_failed+=("xray")
            else
                sudo install -m 0640 -o root -g xray "$tmp" /etc/xray/config.json
                rm -f "$tmp"
                ok "Xray config rendered"
                info "Restarting xray..."
                if sudo systemctl restart xray; then
                    ok "xray restarted"
                else
                    reload_failed+=("xray")
                    warn "Failed: systemctl restart xray"
                fi
            fi
        fi
    fi

    if $FLAG_ALL || $FLAG_PROTON; then
        info "Running systemctl daemon-reload for Proton units..."
        sudo systemctl daemon-reload
        ok "daemon-reload"
        if sudo systemctl is-active proton-keepalive.timer >/dev/null; then
            info "Restarting proton-keepalive.timer..."
            if sudo systemctl restart proton-keepalive.timer; then
                ok "proton-keepalive.timer restarted"
            else
                reload_failed+=("proton-keepalive.timer")
            fi
        else
            skip "proton-keepalive.timer inactive (vpn=off)"
        fi
        if sudo systemctl is-active proton-routing-ensure.timer >/dev/null; then
            info "Restarting proton-routing-ensure.timer..."
            if sudo systemctl restart proton-routing-ensure.timer; then
                ok "proton-routing-ensure.timer restarted"
            else
                reload_failed+=("proton-routing-ensure.timer")
            fi
        else
            skip "proton-routing-ensure.timer inactive (vpn=off)"
        fi
        # is-active distinguishes active-since-cmd_vpn-on from a lingering DOWN
        # interface: restarting the unit on the latter would flip VPN on without
        # going through cmd_vpn's ASN gate or state-file update.
        if sudo systemctl is-active --quiet wg-quick@wg-proton; then
            info "Restarting wg-quick@wg-proton to pick up drop-in..."
            if sudo systemctl restart wg-quick@wg-proton; then
                ok "wg-quick@wg-proton restarted"
            else
                reload_failed+=("wg-quick@wg-proton")
            fi
        else
            skip "wg-quick@wg-proton inactive (vpn=off)"
        fi
    fi

    if [ ${#reload_failed[@]} -gt 0 ]; then
        ntfy_send -t "roost-apply: reload failures" -p "high" \
            "Failed to reload: ${reload_failed[*]}"
    fi

    logger -t "$_HOOK_TAG" "Flag reload complete"
}

# ============================================
# Argument Parsing
# ============================================

AUTO_CONFIRM=false
SUBCOMMAND=""
FILE_FILTERS=()
FLAG_ALL=false
FLAG_CLOUDFLARE=false
FLAG_CADDY=false
FLAG_NTFY=false
FLAG_SYSTEMD=false
FLAG_CRON=false
FLAG_XRAY=false
FLAG_PROTON=false
HAS_FLAGS=false

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<'USAGE'
Usage: roost-apply [diff|push|list] [file-filter...]
       roost-apply [--all] [--cloudflare] [--caddy] [--ntfy] [--systemd] [--cron] [--xray] [--proton]

Subcommands (manifest-based file deployment):
  diff     Show differences between repo and deployed files (default)
  push     Deploy changed files (shows preview, confirms)
  list     List all managed files

Flags (direct service reload):
  --all        Reload all services
  --cloudflare Assemble fragments and restart cloudflared
  --caddy      Reload-or-restart Caddy
  --ntfy       Restart ntfy
  --systemd    Daemon-reload and restart systemd units
  --cron       No-op (cron auto-reloads)
  --xray       Re-render /etc/xray/config.json from state.env and restart xray
  --proton     Daemon-reload, restart proton-keepalive.timer + proton-routing-ensure.timer + wg-quick@wg-proton (if up)

Options:
  -y, --yes    Skip confirmation prompts (push only)
USAGE
            exit 0
            ;;
        -y|--yes) AUTO_CONFIRM=true ;;
        --all)        FLAG_ALL=true; HAS_FLAGS=true ;;
        --cloudflare) FLAG_CLOUDFLARE=true; HAS_FLAGS=true ;;
        --caddy)      FLAG_CADDY=true; HAS_FLAGS=true ;;
        --ntfy)       FLAG_NTFY=true; HAS_FLAGS=true ;;
        --systemd)    FLAG_SYSTEMD=true; HAS_FLAGS=true ;;
        --cron)       FLAG_CRON=true; HAS_FLAGS=true ;;
        --xray)       FLAG_XRAY=true; HAS_FLAGS=true ;;
        --proton)     FLAG_PROTON=true; HAS_FLAGS=true ;;
        diff|push|list)
            if [ -z "$SUBCOMMAND" ]; then
                SUBCOMMAND="$arg"
            else
                FILE_FILTERS+=("$arg")
            fi
            ;;
        -*)
            echo "Unknown flag: $arg" >&2
            exit 1
            ;;
        *) FILE_FILTERS+=("$arg") ;;
    esac
done

# Validate: subcommands and flags are mutually exclusive
if [ -n "$SUBCOMMAND" ] && [ "$HAS_FLAGS" = true ]; then
    echo "Error: subcommands (diff/push/list) and flags (--caddy etc.) are mutually exclusive" >&2
    exit 1
fi

# ============================================
# Dispatch
# ============================================

if [ "$HAS_FLAGS" = true ]; then
    cmd_flag_reload
else
    # Subcommand mode requires the repo
    if [ ! -d "$REPO_DIR/files" ]; then
        echo "Error: Repo not found at $REPO_DIR/" >&2
        echo "Expected the server repo at \$ROOST_DIR/code/server/" >&2
        exit 1
    fi
    case "${SUBCOMMAND:-diff}" in
        diff) cmd_diff ;;
        push) cmd_push ;;
        list) cmd_list ;;
    esac
fi
